name: Deploy Devnet

on:
  push:
    branches: [ "devnet" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: docker login -u atletanetwork -p ${{ secrets.REGISTRYPASS }} docker.io


    - name: Build and Push Docker Image
      run: |
          DATE=$(date +%d%m%y)
          HMS=$(date +%H%M%S)
          echo "DATE: $DATE, HMS: $HMS"
          docker build --build-arg BUILD_FEATURES=fast-runtime -t docker.io/atletanetwork/atleta-node:devnet-${DATE}-${HMS} . 
          docker tag docker.io/atletanetwork/atleta-node:devnet-${DATE}-${HMS} docker.io/atletanetwork/atleta-node:devnet-latest
          docker push docker.io/atletanetwork/atleta-node:devnet-${DATE}-${HMS}
          docker push docker.io/atletanetwork/atleta-node:devnet-latest
    
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.DEVNET_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.DEVNET_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: Copy Files to Server
      run: |
        scp deploy/devnet/docker-compose.yml ${{ secrets.DEVNET_USERNAME}}@${{ secrets.DEVNET_HOST }}:/sportchain/docker-compose.yml
        scp chainspecs/chain-spec.devnet.json ${{ secrets.DEVNET_USERNAME}}@${{ secrets.DEVNET_HOST }}:/sportchain/chainspec.json
        
    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEVNET_HOST }}
        username: ${{ secrets.DEVNET_USERNAME }}
        key: ${{ secrets.DEVNET_PRIVATE_KEY }}
        script: |
          cd /sportchain
          docker compose down
          docker compose pull
          docker compose up -d --build --remove-orphans
